name: Format & Lint & Build
on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
  workflow_call:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install Pnpm
        run: npm install -g pnpm
      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile
      - name: Run prettier
        run: pnpm run format

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install Pnpm
        run: npm install -g pnpm
      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile
      - name: Run eslint
        run: pnpm run lint

  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install Pnpm
        run: npm install -g pnpm
      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build-tsc