name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  check:
    name: Run format & lint & build check
    uses: dashbrains/halo/.github/workflows/format_lint.yml@main
  publish:
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dashbrains'
          cache: 'pnpm'
      - name: Installing Node.js dependencies
        run: pnpm install --frozen-lockfile
      - name: Build package
        run: pnpm build
      - name: Publish package
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}